// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeRepo.Data;

#nullable disable

namespace PokeRepo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240207135539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokeRepo.Models.AbilityDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokeRepo.Models.PokemonAbilityModel", b =>
                {
                    b.Property<int>("PokemonDbModelId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityDbModelId")
                        .HasColumnType("int");

                    b.HasKey("PokemonDbModelId", "AbilityDbModelId");

                    b.HasIndex("AbilityDbModelId");

                    b.ToTable("PokemonAbilities");
                });

            modelBuilder.Entity("PokeRepo.Models.PokemonDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokeRepo.Models.SpeciesDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("PokeRepo.Models.PokemonAbilityModel", b =>
                {
                    b.HasOne("PokeRepo.Models.AbilityDbModel", "AbilityDbModel")
                        .WithMany("PokemonsAbility")
                        .HasForeignKey("AbilityDbModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRepo.Models.PokemonDbModel", "PokemonDbModel")
                        .WithMany("PokemonAbilityModels")
                        .HasForeignKey("PokemonDbModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityDbModel");

                    b.Navigation("PokemonDbModel");
                });

            modelBuilder.Entity("PokeRepo.Models.PokemonDbModel", b =>
                {
                    b.HasOne("PokeRepo.Models.SpeciesDbModel", "Species")
                        .WithMany("PokemonDbModels")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeRepo.Models.SpeciesDbModel", b =>
                {
                    b.HasOne("PokeRepo.Models.PokemonDbModel", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeRepo.Models.AbilityDbModel", b =>
                {
                    b.Navigation("PokemonsAbility");
                });

            modelBuilder.Entity("PokeRepo.Models.PokemonDbModel", b =>
                {
                    b.Navigation("PokemonAbilityModels");
                });

            modelBuilder.Entity("PokeRepo.Models.SpeciesDbModel", b =>
                {
                    b.Navigation("PokemonDbModels");
                });
#pragma warning restore 612, 618
        }
    }
}
